name: Fensterkitt
title: Fensterkitt Support App
version: '11.0.0'
summary: An easy to use, cross-platform remote desktop assistance solution
description: |
  Fensterkitt Support App for easy remote assistance.

  Its key features are
  - no router or network configuration required
  - friendly, multilingual (de/en/es/fr/it/ru/tr/zh) user interface
  - secure, encrypted communication (TLS)
license: GPL-3.0
grade: stable
base: core18
confinement: strict

apps:
  assisted:
    extensions:
      [gnome-3-28]
    command: bin/dayon.launcher $SNAP/jar/dayon.jar mpo.dayon.assisted.AssistedRunner $1 $2 $3
    desktop: ../parts/dayon/build/target/dayon.assisted.desktop
    plugs:
      [home, network, desktop]

  browser:
    extensions:
      [gnome-3-28]
    command: bin/dayon.browser
    plugs:
      [home, network, desktop]

parts:
  dayon:
    plugin: maven
    source: https://github.com/retgal/dayon.git
    source-tag: fensterkitt
    source-type: git
    maven-options:
      [-Psnap]
    override-build: |
      snapcraftctl build
      cp target/dayon.browser ../install/bin/
      cp target/dayon.launcher ../install/bin/
      cp target/dayon.png ../install/bin/
    filesets:
      exclude-original-jar:
        [-jar/original-dayon.jar]
    stage:
      [$exclude-original-jar]
    stage-packages:
      [default-jre]
